# Generated by Django 4.2.7 on 2024-01-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage_app', '0007_remove_device_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
