version: '3'

services:
  backend:
    build:
      context: ./backend_Project
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./backend_Project/backend:/backend
    command: python3 /backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    tty: true
  frontend:
    build:
      context: ./frontend_Project
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./frontend_Project/node/frontend/signage_app:/usr/src/app/frontend/signage_app
    command: sh -c "cd /usr/src/app/frontend/signage_app && yarn start"
    ports:
      - "3000:3000"
