# Generated by Django 4.2.7 on 2023-11-25 13:58

from django.db import migrations, models
import signage_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('signage_app', '0003_rename_file_path_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=signage_app.models.content_file_name),
        ),
    ]
