# Generated by Django 4.2.7 on 2023-12-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signage_app', '0004_alter_content_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentgroupmember',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='content',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='device',
        ),
        migrations.AddField(
            model_name='content',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signage_app.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(default='未公開', max_length=50),
        ),
        migrations.AddField(
            model_name='contentgroup',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signage_app.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentgroup',
            name='status',
            field=models.CharField(default='未公開', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='contentgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='signage_app.contentgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='signage_app.content'),
        ),
    ]
