# Generated by Django 4.2.7 on 2023-12-18 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('signage_app', '0004_alter_content_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentgroupmember',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='content',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='device',
        ),
        migrations.AddField(
            model_name='content',
            name='device',
            field=models.ForeignKey(default=datetime.datetime(2023, 12, 18, 6, 44, 18, 36989, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='signage_app.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentgroup',
            name='device',
            field=models.ForeignKey(default=datetime.datetime(2023, 12, 18, 6, 44, 28, 397177, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='signage_app.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='content_type',
            field=models.ForeignKey(default=datetime.datetime(2023, 12, 18, 6, 44, 39, 196080, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='object_id',
            field=models.PositiveIntegerField(default=datetime.datetime(2023, 12, 18, 6, 44, 47, 813744, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
