# Generated by Django 4.2.7 on 2023-12-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage_app', '0006_device_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='serial_number',
        ),
    ]
