# Generated by Django 4.2.7 on 2023-12-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signage_app', '0005_signage_signagecontent_signage_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signagecontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='signagecontent',
            name='signage',
        ),
        migrations.AlterModelOptions(
            name='contentgroupmember',
            options={'ordering': ['order']},
        ),
        migrations.DeleteModel(
            name='Signage',
        ),
        migrations.DeleteModel(
            name='SignageContent',
        ),
    ]
